apiVersion: v1
kind: Service
metadata:
  name: ml-api-service
  labels:
    app: ml-api
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    name: http
  selector:
    app: ml-api
---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ml-api-deployment
spec:
  selector:
    matchLabels:
      app: ml-api
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: ml-api
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - name: ml-api
        image: nexus.teamdigitale.test/ml-api:0.1.1
        ports:
        - name: http
          containerPort: 5000
        resources:
          limits:
            memory: 2Gi
            cpu: 2
          requests:
            memory: 2Gi
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "nifi"
                  operator: NotIn
                  values: ["true"]
